### PR TITLE
Import vpn files

### PR DESCRIPTION
**Pull request by Pekkari**
The following PR is the follow up from indicator-network/#41, which targets
the import of an openvpn file in the indicator network service, by importing
the example of file import using libnm. I also allow multiple plugins to be used
to parse the file, which open the opportunity to try to import config files of
other well-known vpn software.

### CODE REVIEW

**Comment by Pekkari** [comment]
I caught errors here that doesn't seem to be related to my change:
```
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp: In member function ‘virtual void {anonymous}::TestConnectivityApi_HotspotConfig_Test::TestBody()’:
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp:500:28: error: ‘NM_DBUS_IFACE_SETTINGS’ was not declared in this scope
                            NM_DBUS_IFACE_SETTINGS,
                            ^
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp:571:28: error: ‘NM_DBUS_IFACE_SETTINGS_CONNECTION’ was not declared in this scope
                            NM_DBUS_IFACE_SETTINGS_CONNECTION,
                            ^
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp: In member function ‘virtual void {anonymous}::TestConnectivityApi_InsecureHotspotConfig_Test::TestBody()’:
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp:655:28: error: ‘NM_DBUS_IFACE_SETTINGS’ was not declared in this scope
                            NM_DBUS_IFACE_SETTINGS,
                            ^
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp:720:28: error: ‘NM_DBUS_IFACE_SETTINGS_CONNECTION’ was not declared in this scope
                            NM_DBUS_IFACE_SETTINGS_CONNECTION,
                            ^
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp: In member function ‘virtual void {anonymous}::TestConnectivityApi_HotspotModemAvailable_Test::TestBody()’:
/home/phablet/indicator-network/tests/integration/test-connectivity-api.cpp:750:28: error: ‘NM_DBUS_IFACE_SETTINGS’ was not declared in this scope
                            NM_DBUS_IFACE_SETTINGS,
                            ^
```
It would be great if somebody can have a look.

**Comment by Flohack74** [comment]
Just for clarification, this PR contains also changes from #41 - if we would merge this here, would the other one be obsolete then? And, in the other way round, too... If this PR needs changes from the other one to work, please put it up as draft, o rgive otherwise instructions that this i snot just merged as-is.
in another note, I cannot see how this change will actually allow choosing an input file by the UI. Can you give me a rundown on how that will work from a user perspective?

**Comment by Pekkari** [comment]
@manland can confirm, as in further discussion, he didn't work in the PR #41, which means in practice this PR is making it obsolete.

You are right, this doesn't offer the GUI, for that it is [system-settings/#272](https://gitlab.com/ubports/core/lomiri-system-settings/-/merge_requests/272). That offers a button to import a file, with a listview to select the file, and the opportunity to add some user/password if the authentication method is that one in openvpn. It will eventually call the function I modify in my commit, and this function will attempt to use any vpn module available to import the file in network manager.

Please let me know if you need further clarification, or there is any other questions to address.

**Comment by Flohack74** [comment]
Alright I understand so I will close #41 and target this for OTA-19. I will also target the GUI part...

**Comment by Flohack74** [comment]
Also the branch name should be xenial_-_xyz so that our Ci knows which image to select for building. Important is the _-_ part. Can you please rename that branch and reopen the PR on top of it? Sorry for the complications!

**Comment by Pekkari** [comment]
No problem. I'll close this and ping you in the new one.

**Pull request closed without merging**
