### PR TITLE
Fix locale dir usage so that translations will be loaded.

### LINKED ISSUE #12: Untranslated string
On Xenial dev 669, a string «Cellular Data» is not translated even if it's in the po
Needs to update translations?

imatge

### PR DESCRIPTION
**Pull request by dobey**
Fixes #12

### CODE REVIEW

**Comment by Flohack74** [comment]
Should we leave the comment "fixes 12" even if the translations come from the langpack? Also I wonder why other indicators dont have this issue.

**Comment by dobey** [comment]
> Also I wonder why other indicators dont have this issue.

They do. Remove the langpack from your device and reboot, and you'll see lots of things no longer translated.

**Comment by dobey** [comment]
> Should we leave the comment "fixes 12" even if the translations come from the langpack?

OK, apparently I messed something up and didn't actually test the fixed build on Saturday, and after spending time on this today discovered that it does in fact work properly with my fix. So please review now. :)

**Review by Flohack74 — APPROVED** [review]

**Comment by svenha** [comment]
OTA-14 2020-W43 on OP3T:
issue is fixed

**Pull request merged**
